server:
  port: 8010
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: multiple-intancias
          search-paths: config-data
          uri: https://github.com/jesusabo/microserviciosRepo
          username: jesusabo
          password: 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
          clone-on-start: true
