server:
  port: 8010
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          default-label: gateway
          search-paths: config-data
          uri: https://github.com/jesusabo/microserviciosRepo
